"""Configuration loader — reads and validates aideploy.yaml."""

from __future__ import annotations

import logging
from pathlib import Path

import yaml
from pydantic import ValidationError

from aideploy.config.schema import AideployConfig
from aideploy.constants import CONFIG_FILE
from aideploy.exceptions import ConfigError, ConfigNotFoundError

logger = logging.getLogger(__name__)


def load_config(project_dir: Path | None = None) -> AideployConfig:
    """Load and validate aideploy.yaml from *project_dir* (default: cwd).

    Raises:
        ConfigNotFoundError: If aideploy.yaml does not exist.
        ConfigError: If the file cannot be parsed or fails validation.
    """
    directory = project_dir or Path.cwd()
    config_path = directory / CONFIG_FILE

    if not config_path.exists():
        raise ConfigNotFoundError()

    logger.debug("Loading config from %s", config_path)

    try:
        raw = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ConfigError(
            f"Failed to parse {CONFIG_FILE}: {exc}",
            hint="Check the YAML syntax of your aideploy.yaml.",
        ) from exc

    if not isinstance(raw, dict):
        raise ConfigError(
            f"{CONFIG_FILE} must be a YAML mapping, got {type(raw).__name__}.",
            hint="Ensure aideploy.yaml contains key-value pairs at the top level.",
        )

    try:
        config = AideployConfig.model_validate(raw)
    except ValidationError as exc:
        # Format validation errors into a readable message
        errors = _format_validation_errors(exc)
        raise ConfigError(
            f"Configuration validation failed:\n\n{errors}",
            hint=f"Edit {CONFIG_FILE} to fix the above issues.",
        ) from exc

    logger.debug("Config loaded: project=%s", config.name)
    return config


def _format_validation_errors(exc: ValidationError) -> str:
    """Format Pydantic ValidationError into a human-readable string."""
    lines: list[str] = []
    for error in exc.errors():
        loc = " → ".join(str(p) for p in error["loc"]) if error["loc"] else "(root)"
        msg = error["msg"]
        lines.append(f"  [{loc}] {msg}")
    return "\n".join(lines)


def write_config(config: AideployConfig, project_dir: Path | None = None) -> Path:
    """Write an AideployConfig to aideploy.yaml.

    Returns:
        Path to the written file.

    Raises:
        ConfigError: If the file already exists (call-site must handle overwrite logic).
    """
    directory = project_dir or Path.cwd()
    config_path = directory / CONFIG_FILE

    data = config.model_dump(exclude_none=True)
    yaml_text = _to_yaml_with_comments(data, config)

    config_path.write_text(yaml_text, encoding="utf-8")
    logger.debug("Config written to %s", config_path)
    return config_path


def _to_yaml_with_comments(data: dict, config: AideployConfig) -> str:
    """Render the config dict as an annotated YAML string."""
    lines = [
        "# AIDeploy configuration — generated by `aideploy init`",
        "# Edit this file to customise your deployment.",
        "#",
        "# Documentation: https://github.com/your-org/aideploy",
        "",
        f"name: {config.name}",
        "",
        "runtime:",
        f'  python: "{config.runtime.python}"',
        "",
        "app:",
        f'  entrypoint: "{config.app.entrypoint}"',
        f"  port: {config.app.port}",
        "",
        "health:",
        f'  path: "{config.health.path}"',
        f"  timeout: {config.health.timeout}",
        f"  retries: {config.health.retries}",
        f"  interval: {config.health.interval}",
        "",
    ]

    if config.environment:
        lines.append(
            "# Environment variables — values come from your local environment."
        )
        lines.append(
            "# Do NOT put secrets directly in this file."
        )
        lines.append("environment:")
        for var in config.environment:
            lines.append(f"  - {var}")
        lines.append("")

    lines += [
        "deployment:",
        f"  strategy: {config.deployment.strategy}",
    ]
    if config.deployment.region:
        lines.append(f"  region: {config.deployment.region}")
    lines.append("")

    lines += [
        "cost:",
        f"  max_monthly: {config.cost.max_monthly}",
        "  # AIDeploy aims to minimize cost but cannot guarantee $0.",
        "  # See README for the cost model.",
        "",
    ]

    return "\n".join(lines)
