"""Docker image builder.

Responsibilities:
- Generate a sensible Dockerfile if one doesn't exist
- Build the Docker image
- Tag the image deterministically
- Never embed secrets into image layers
"""

from __future__ import annotations

import logging
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from aideploy.config.schema import AideployConfig
from aideploy.constants import DEFAULT_APP_PORT, DOCKERFILE_NAME, DOCKER_IMAGE_LABEL
from aideploy.exceptions import DockerBuildError, DockerNotAvailableError

logger = logging.getLogger(__name__)

# ── Dockerfile templates ───────────────────────────────────────────────────────

_DOCKERFILE_TEMPLATE = """\
# Generated by AIDeploy — edit freely but do not embed secrets.
# Re-generate: aideploy init --force

FROM python:{python_version}-slim

# Security: run as non-root
RUN groupadd --gid 1001 appuser && \\
    useradd --uid 1001 --gid 1001 --no-create-home appuser

WORKDIR /app

# Install dependencies first (cache layer)
COPY {deps_file} .
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -r {deps_file}

# Copy application code
COPY . .

# Remove any local .env files that may have been copied
RUN find /app -name ".env*" -type f -delete

USER appuser

EXPOSE {port}

# Run with uvicorn — do NOT use --reload in production
CMD ["python", "-m", "uvicorn", "{entrypoint}", "--host", "0.0.0.0", "--port", "{port}"]
"""

_DOCKERFILE_PYPROJECT_TEMPLATE = """\
# Generated by AIDeploy — edit freely but do not embed secrets.
# Re-generate: aideploy init --force

FROM python:{python_version}-slim

RUN groupadd --gid 1001 appuser && \\
    useradd --uid 1001 --gid 1001 --no-create-home appuser

WORKDIR /app

# Install build tools
RUN pip install --no-cache-dir --upgrade pip

# Copy and install the project
COPY pyproject.toml .
COPY . .
RUN pip install --no-cache-dir ".[all]" 2>/dev/null || pip install --no-cache-dir .

# Remove any local .env files
RUN find /app -name ".env*" -type f -delete

USER appuser

EXPOSE {port}

CMD ["python", "-m", "uvicorn", "{entrypoint}", "--host", "0.0.0.0", "--port", "{port}"]
"""


def generate_dockerfile(
    config: AideployConfig,
    project_dir: Path | None = None,
) -> str:
    """Generate Dockerfile content for a FastAPI application.

    Args:
        config: Validated AIDeploy configuration.
        project_dir: Project root (defaults to cwd).

    Returns:
        Dockerfile content as a string.
    """
    directory = project_dir or Path.cwd()
    entrypoint = config.app.entrypoint  # e.g. "app.main:app"
    port = config.app.port
    python_version = config.runtime.python

    has_requirements = (directory / "requirements.txt").exists()
    has_pyproject = (directory / "pyproject.toml").exists()

    if has_requirements:
        return _DOCKERFILE_TEMPLATE.format(
            python_version=python_version,
            deps_file="requirements.txt",
            entrypoint=entrypoint,
            port=port,
        )
    elif has_pyproject:
        return _DOCKERFILE_PYPROJECT_TEMPLATE.format(
            python_version=python_version,
            entrypoint=entrypoint,
            port=port,
        )
    else:
        # Fallback — no known dependency file
        return _DOCKERFILE_TEMPLATE.format(
            python_version=python_version,
            deps_file="requirements.txt",
            entrypoint=entrypoint,
            port=port,
        )


def write_dockerfile(
    config: AideployConfig,
    project_dir: Path | None = None,
    force: bool = False,
) -> tuple[Path, bool]:
    """Write a generated Dockerfile to *project_dir*.

    Args:
        config: Validated configuration.
        project_dir: Project root (defaults to cwd).
        force: Overwrite existing Dockerfile if True.

    Returns:
        (path, was_generated) — was_generated is False if an existing
        Dockerfile was kept.
    """
    directory = project_dir or Path.cwd()
    dockerfile_path = directory / DOCKERFILE_NAME

    if dockerfile_path.exists() and not force:
        logger.debug("Existing Dockerfile found — not overwriting.")
        return dockerfile_path, False

    content = generate_dockerfile(config, directory)
    dockerfile_path.write_text(content, encoding="utf-8")
    logger.debug("Dockerfile written to %s", dockerfile_path)
    return dockerfile_path, True


# ── Image tagging ──────────────────────────────────────────────────────────────


def make_image_tag(project_name: str, deployment_id: str) -> str:
    """Create a deterministic, mutable-tag-free image tag.

    Format: ``{project_name}:{deployment_id}``

    The tag is also labelled with DOCKER_IMAGE_LABEL to identify AIDeploy images.
    """
    safe_name = re.sub(r"[^a-z0-9_.-]", "-", project_name.lower())
    return f"{safe_name}:{deployment_id}"


def make_ecr_image_uri(ecr_repo_uri: str, deployment_id: str) -> str:
    """Construct the full ECR image URI for pushing/pulling."""
    return f"{ecr_repo_uri}:{deployment_id}"


# ── Docker availability ────────────────────────────────────────────────────────


def check_docker_available() -> None:
    """Verify Docker is running and accessible.

    Raises:
        DockerNotAvailableError: If Docker is not available.
    """
    try:
        result = subprocess.run(
            ["docker", "info", "--format", "{{.ServerVersion}}"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            raise DockerNotAvailableError()
        logger.debug("Docker server version: %s", result.stdout.strip())
    except FileNotFoundError:
        raise DockerNotAvailableError() from None
    except subprocess.TimeoutExpired:
        raise DockerNotAvailableError() from None


# ── Image building ─────────────────────────────────────────────────────────────


def build_image(
    image_tag: str,
    project_dir: Path | None = None,
    platform: str = "linux/amd64",
    progress_callback=None,
) -> str:
    """Build a Docker image for the FastAPI application.

    Args:
        image_tag: Full image tag (name:tag).
        project_dir: Build context directory.
        platform: Target platform (must be linux/amd64 for App Runner).
        progress_callback: Optional callable(line: str) for streaming output.

    Returns:
        The image tag on success.

    Raises:
        DockerBuildError: If the build fails.
        DockerNotAvailableError: If Docker is not available.
    """
    check_docker_available()

    directory = project_dir or Path.cwd()
    dockerfile_path = directory / DOCKERFILE_NAME

    if not dockerfile_path.exists():
        raise DockerBuildError(
            f"No Dockerfile found at {dockerfile_path}.",
            hint="Run `aideploy init` to generate a Dockerfile, or create one manually.",
        )

    cmd = [
        "docker", "build",
        "--platform", platform,
        "--tag", image_tag,
        "--label", f"{DOCKER_IMAGE_LABEL}=true",
        "--file", str(dockerfile_path),
        str(directory),
    ]

    logger.debug("Running: %s", " ".join(cmd))

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        output_lines: list[str] = []
        assert process.stdout is not None
        for line in process.stdout:
            line = line.rstrip()
            output_lines.append(line)
            logger.debug("[docker build] %s", line)
            if progress_callback:
                progress_callback(line)

        process.wait()
        if process.returncode != 0:
            tail = "\n".join(output_lines[-30:])
            raise DockerBuildError(
                f"Docker build failed (exit code {process.returncode}).\n\n"
                f"Last output:\n{tail}",
                hint=(
                    "Check the Dockerfile for errors.\n"
                    "Run `docker build .` manually for full output."
                ),
            )
    except FileNotFoundError:
        raise DockerNotAvailableError() from None

    logger.info("Docker image built: %s", image_tag)
    return image_tag
